name: matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:slim
    outputs:
      build-output: ${{ steps.step1.outputs.BUN_VER_OUT }}
    steps:
      - name: output
        id: step1
        run: |
          bunver=$(bun --version)
          echo "BUN_VER_OUT=$bunver" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test output
        id: step2
        run: echo ${{ needs.build.outputs.build-output }}
  concurrency1:
    runs-on: ubuntu-latest
    concurrency: 
      group: concur-group1
    steps:
      - name: test concurrency1
        id: step3
        run: sleep 15
        
  concurrency2:
    runs-on: ubuntu-latest
    concurrency: 
      group: concur-group1
    steps:
      - name: test concurrency2
        id: step3
        run: sleep 15

  
