# This is a basic workflow to help you get started with Actions

name: matrix

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  matrix-job:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]
        include:
          - runner: macos-latest
            python-version: 3.12
        exclude:
          - runner: windows-latest
            python-version: 3.13
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo This job will run in the python vesrion ${{ matrix.python-version }}
